= The `DEVICE` signature
:Author: David MacQueen
:Date: 2024.2.18
:stem: latexmath
:source-highlighter: pygments
:stylesheet: smlnj-lib-base.css
:VERSION: 10.2

`DEVICE` is the signature for device classes (currently limited to two choices: `Plain_Device` and `ANSITerm_Device`).

== Synopsis

[source,sml]
----
signature DEVICE
structure Plain_Device : DEVICE 
structure ANSITerm_Device : DEVICE

Imports: Token, MODE

structure Mode : MODE

type device

exception# DeviceError

val mkDevice : TextIO.outstream -> int -> device

val resetDevice : device -> unit

val width : device -> int

val space : device -> int -> unit

val indent : device -> int -> unit

val newline : device -> unit

val string : device -> string -> unit

val token : device -> Token.token -> unit

val flush : device -> unit

(* 'r will instantiate to a "renderState" type *)
(* potentially raises DeviceError *)
val renderStyled : device -> Mode.mode * (unit -> 'r)  -> 'r
----

== Description

`[.kw]#structure# Mode : MODE`::
The device mode (or _physical_ style).

`[.kw]#type# device`::
The type of a device value (abstract).	     

`[.kw]#exception# DeviceError`::
An exception potentially raised internally by the `renderStyled` function, signaling
that the device is in a bad state.

`[.kw]#val# mkDevice : TextIO.outstream -> int -> device`::
To create a device, we provide an outstream and a line width.

`[.kw]#val# resetDevice : device -> unit`::
Used to reset the internal state (if any) of a device.

`[.kw]#val# width : device -> int`::
Returns the line width associated with the device.

`[.kw]#val# space : device -> int -> unit`::
`space dev n` outputs n spaces to the device's outstream.

`[.kw]#val# indent : device -> int -> unit`::
`indent dev n` outputs n spaces to the device's outstream (assumed after newline).

`[.kw]#val# newline : device -> unit`::
`newline dev` outputs a newline to the device's outstream.

`[.kw]#val# string : device -> string -> unit`::
`string dev ` outputs string s to the device's outstream.

`[.kw]#val# token : device -> Token.token -> unit`::
`token dev tok` outputs the base string of token `tok` to the device's outstream.

`[.kw]#val# flush : device -> unit`::
`flush dev` flushes any pending output to the device's outstream.

`[.kw]#val# renderStyled : device -> Mode.mode * (unit -> 'r)  -> 'r`::
`renderStyled dev (mode, thunk)` forces the rendering thunk with layered mode applied to
the device. Potentially raises DeviceError.
(`'r` will instantiate to a `renderState` type)

== See Also

xref:sig-MODE.adoc[`[.kw]#signature# MODE`]
