= The `Formatting` structure
:Author: David MacQueen
:Date: 2024.2.13
:stem: latexmath
:stylesheet: smlnj-lib-base.css
:source-highlighter: pygments
:VERSION: 10.2

The `Formatting` structure is the main user-facing module of the new prettyprinter
library. It provides facilities for defining mappings from data structures to _formats_
(of type `Format.format`), which will then be _rendered_, either to produce output on some
_device_, or to produce another formatted file, such as an HTML file.

== Synopsis

[source,sml]
----
signature FORMATTING
structure Formatting :> FORMATTING

Imports: Token

type format  (* abstract *)

datatype alignment  (* alignment property of "aligned" blocks *)
  = H  (* Horizontal alignment, with implicit single space separtors between format components *)
  | V  (* Vertical alignment, with implicit hardline separtors between format components *)
  | P  (* Packed alignment, with implicit softline separtors between format components *)
  | C  (* compact, no breaks between block format elements *)

datatype break       (* separate format elements in a basic block, allowing line breaks *)
  = Hard         (* hard line break *)
  | Soft of int  (* soft line break; rendered to n spaces when not triggered, where n >= 0 *)
  | Space of int     (* n spaces, where n >= 0 *)
  | Null

datatype element
  = BRK of break  (* breaks are _not_, and do not contain, content *)
  | FMT of format

val empty : format            (* == EMPTY, renders as empty string, composition identity *)
val text : string -> format   (* == the TEXT format constructor *)
val token : Token.token -> format  (* == the TOKEN format constructor *)
val integer : int -> format   (* integer n renders as Int.toString n *)
val string : string -> format (* adds double quotes *)
val char : char -> format     (* c --> #"c" *)
val bool : bool -> format     (* true --> TEXT "true", false --> TEXT "false" *)

val block : element list -> format  (* basic block construction *)
val aBlock : alignment -> format list -> format  (* aligned block construction *)

val hBlock : format list -> format   (* = aBlock H *)
val vBlock : format list -> format   (* = aBlock V *)
val pBlock : format list -> format   (* = aBlock P *)
val cBlock : format list -> format   (* = aBlock C *)

val comma : format     (* text "," *)
val colon : format     (* text ":" *)
val semicolon : format (* text ";" *)
val period : format    (* text "." *)
val equal : format     (* text "=", an honorary punctuation mark *)

val lparen : format    (* text "(" *)
val rparen : format    (* text ")" *)
val lbracket : format  (* text "[" *)
val rbracket : format  (* text "]" *)
val lbrace : format    (* text "{" *)
val rbrace : format    (* text "}" *)
val langle : format    (* text "<" *)
val rangle : format    (* text ">" *)

val spaces : int -> format

val enclose : {front: format, back: format} -> format -> format
val parens : format -> format
val brackets : format -> format
val braces : format -> format
val angleBrackets : format -> format

val appendNewLine : format -> format
val label : string -> format -> format

val sequence : alignment -> format -> format list -> format
val hSequence : format -> format list -> format
val pSequence : format -> format list -> format
val vSequence : format -> format list -> format
val cSequence : format -> format list -> format

val tuple  : format list -> format
val list   : format list -> format
val option : format option -> format

val vHeaders : {header1: string, header2: string} -> format list -> format

val indent : int -> format -> format

val tryFlat : format -> format
val alt : format * format -> format
val hvBlock : format list -> format

val styled : string -> format -> format
----

== Description

`[.kw]#type# format`::
  The type constructor for formats (= Format.format).

`[.kw]#datatype# break = Hard | Soft of int | Space of int | Null`::
  The type of breaks in basic blocks.

`[.kw]#datatype# element = FMT of format | BRK of break`::
  The type of elements making up a basic block, either a format or a break.

`[.kw]#datatype# alignment = H | P | V | C`::
  The type of alignments in aligned blocks: horizontal, packed, vertical, and compact.

`[.kw]#val# empty : format`::
  The empty format that prints nothing when rendered, equivalent to (`text ""`). Empty formats are
  absorbed by adjacent nonempty formats, so that no "separation" whitespace will be printed between and
  empty format and adjacent nonempty formats. Empty serves as an identity element for binary
  format concatenation operators. For instance, `hBlock (fmt, empty) == fmt`.

`[.kw]#val# text : string \-> format`::
  Create an atomic "text" block consisting of a string, which renders as that string.
  Note that the string may contain, indeed may consist only of, white space.  As a mater
  of style, however, whitespace should usually be produced by formatting rather than being
  built into text strings.
 
`[.kw]#val# block : element list \-> format`::
  Build a block with _ad hoc_ alignment determined by explicit breaks among the elements.

`[.kw]#val# aBlock : alignment \-> format list \-> format`::
  Build an aligned block with the specified alignment and format components.

`[.kw]#val# hBlock : format list \-> format`::
  `hBlock fmts` : Create a horizontally aligned block (with implicit (Space 1) breaks) with
  fmts as components.

`[.kw]#val# vBlock : format list \-> format`::
  `vBlock fmts` : Create a vertically aligned block (with implicit Hard breaks) with
  fmts as components.

`[.kw]#val# pBlock : format list \-> format`::
  `pBlock fmts` : Create a "packed" aligned block (with implicit (Soft 1) breaks) with fmts
  as components.

`[.kw]#val# cBlock : format list \-> format`::
  `cBlock fmts` : Create a "compact" aligned block with fmts as components, with no breaks
  between components.

////
`[.kw]#val# flat : format \-> format`::
  `flat fmt` : Returns a version of the argument fmt that will be rendered as flat
  (on a single line) and will have the same flat measure.
////
`[.kw]#val# comma, colon, semicolon, period, lparen, rparen, lbracket, rbracket, lbrace, rbrace, equal : format`::
  Punctuation characters as formats (plus the equal symbol, an honorary punctuation symbol).

`[.kw]#val# integer : int \-> format`::
  `integer n` : Returns the string representation of n (`Int.toString n`) as a text format.

`[.kw]#val# string : string \-> format`::
  `string s` : Formats the string `s` enclosed in double quotation marks.

`[.kw]#val# char : char \-> format`::
   `char c` : Formats c as `# ^ (string (Char.toString c))`.

`[.kw]#val# bool : bool \-> format`::
  `bool b` : Formats the boolean b as `true` or `folse`.

`[.kw]#val# enclose : {front: format, back: format} \-> format \-> format`::
  `enclose {front, back} fmt` : Concatenate (`cBlock`) front, fmt, and back.

`[.kw]#val# parens: format \-> format`::
  `parens fmt = enclose {front=lparen, back=rparen} fmt` : Enclose fmt with left and right parentheses.

`[.kw]#val# brackets: format \-> format`::
  `brackets fmt = enclose {front=lbracket, back=rbracket} fmt` : Enclose fmt with left and right square brackets. 

`[.kw]#val# braces: format \-> format`::
  `braces fmt = enclose {front=lbrace, back=rbrace} fmt` : Enclose fmt with left and right curly braces. 

`[.kw]#val# angleBrackets: format \-> format`::
  `angleBrackets fmt = enclose {front=lbrace, back=rbrace} fmt` : Enclose fmt with left and right angle brackets. 

`[.kw]#val# spaces : int \-> format`::
  `spaces n = text <n spaces as string>`, where `n >= 0`.

`[.kw]#val# label : string \-> format \-> format`::
  `label str fmt = hBlock [text str, fmt]`

`[.kw]#val# appendNewLine : format \-> format`::
  Append a hard newline after the format.

`[.kw]#val# sequence : alignment \-> format \-> format list \-> format`::
  `sequence a sep fmts`: Inserts `sep` between constituent formats in `fmts` and aligns according to `a`.

`[.kw]#val# hSequence : format \-> format list \-> format`::
  `hsequence sep fmts`: Inserts `sep` between constituent formats in `fmts` with `H` alignment.

`[.kw]#val# pSequence : format \-> format list \-> format`::
  `psequence sep fmts`: Inserts `sep` between constituent formats in `fmts` with `P` alignment.

`[.kw]#val# vSequence : alignment \-> format \-> format list \-> format`::
  `vsequence sep fmts`: Inserts `sep` between constituent formats in `fmts` with `V` alignment.

`[.kw]#val# cSequence : alignment \-> format \-> format list \-> format`::
  `csequence sep fmts`: Inserts `sep` between constituent formats in `fmts` with `C` alignment.

`[.kw]#val# tuple : format list \-> format`::
  Formats the members of the format list as an SML tuple (parenthesized, with elements
  separated by commas) with default packed (P) alignment of the element formats.

`[.kw]#val# list : format list \-> format`::
  Formats the members of the format list as an SML list (bracketed, with elements
  separated by commas) with default packed (P) alignment of the element formats.

`[.kw]#val# option : format option \-> format`::
  Formats a format option, producing `text "NONE"` or `"SOME(.)"`.

`[.kw]#val# vSequenceLabeled : string list \-> format list \-> format`::
  Vertically align the formats with each format prepended (hBlock) with the corresponding label.
  If there are more labels than formats, the extra labels are ignored;
  if there are fewer labels than formats, the last label is repeated for the remaining formats.

`[.kw]#val# justifyRight : string list \-> string list`::
  Make all labels in the string list agree in length by padding with spaces on the left.
  Typically used to pre-justify labels in conjunction with vSequenceLabeled. 

`[.kw]#val# justifyLeft : string list \-> string list`::
  Make all labels in the string list agree in length by padding with spaces on the right.
  Typically used to pre-justify labels in conjunction with vSequenceLabeled.

`[.kw]#val# indent : int \-> format \-> format`::
  `indent n fmt`: Indent `fmt` `n` additional spaces (relative to the parent block's blm)
  but only if immediately following a line break. Otherwise render `fmt` normally at current location,
  with no line break or indentation; `n >= 0`.

`[.kw]#val# tryFlat : format \-> format`::
  `tryFlat fmt` renders as `(flat fmt)` if that fits, and otherwise renders as `fmt`.

`[.kw]#val# alt : format * format \-> format`::
  `alt (fmt1, fmt2)` renders as `fmt1` if `fmt1` fits, otherwise it renders as `fmt2`.

`[.kw]#val# hvBlock : format list \-> format`::
  `hvblock fmts` renders as `(hBlock fmts)` if that fits, and otherwise renders as `(vBlock fmts)`.

`[.kw]#val# styled : string \-> format \-> format`::
  `styled style format` : render `format` with _logical_ style `style`.

== See Also

xref:prettyprint-manual.adoc[Prettyprint Manual] +
xref:str-Token.html[`[.kw]#structure# Token`]